version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80" # Прокидываем порт на ваш компьютер (localhost:5173)
    volumes:
      - .:/app # Монтируем папку с кодом, чтобы работала горячая перезагрузка (Hot Reload)
      - /app/node_modules # Защищаем node_modules внутри контейнера
    environment:
      - WATCHPACK_POLLING=true # Помогает адекватно отслеживать изменения файлов на Windows/macOS
